oc_user_homepage:
    path:     /
    defaults: { _controller: OCUserBundle:Default:index }


oc_user_cavaliers:
    path:     /profile/admin/cavaliers
    defaults: { _controller: OCUserBundle:Cavaliers:cavaliers }
    
oc_user_cavalier:
    path:     /profile/admin/cavalier/{id}
    defaults: { _controller: OCUserBundle:Cavaliers:fiche }
    requirements:
        id: \d+